name: trailing-commas-build
on: [push, pull_request]
jobs:
  build-py38-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-java@v2
        with:
          python-version: '3.8'
      - name: Build
        run: ./bin/build.sh
  build-py36-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-java@v2
        with:
          python-version: '3.6'
      - name: Setup
        run: python -m pip install -r test-requirements.txt
      - name: Build
        run: ./bin/build.sh
  build-py27-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-java@v2
        with:
          python-version: '2.7'
      - name: Build
        run: ./bin/build.sh
