name: trailing-commas-build
on: [push, pull_request]
jobs:
  build-py38-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '2.7', '3.x', 'pypy-2.7', 'pypy-3.7', 'pypy-3.8' ]
        # exclude:
        #   - os: macos-latest
        #     python-version: '3.8'
        #   - os: windows-latest
        #     python-version: '3.6'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup
        run: python -m pip install -r test-requirements.txt
      - name: Build
        run: ./bin/build.sh
